name: Cypress Tests - In Class Project

on:
  push:
    branches:
      - main
    paths:
      - 'Cypress_tests/**.js'
      - 'Cypress_tests/**.json'
      - 'Cypress_tests/**.yml'

jobs:
  Cypress_tests-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1

      - name: Install dependencies
        run: npm install
        working-directory: ./Cypress_tests

      - name: Run Cypress tests
        run: npm run cypress:headless
        working-directory: ./Cypress_tests